# Generated by Django 2.2.4 on 2019-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='senha')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
